---
title: "June 2023 Prelim Visualizations"
author: "Michael Yonker"
date: "6/30/23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/cloud/project")
```

```{r load-packages, message= F, include=F}
library(tidyverse)
library(tidymodels)
library(ggh4x)
library(lubridate)
```

```{r read-data, message = F, include = F}
flux_june <- read_csv("data/230607/230607_fluxes.csv")
photo_june <- read_csv("data/230607/230607_photosynthesis.csv")
#co2 <- read_csv("data/230607/230607_co2_fluxes.csv")
```

```{r flux-plots}
flux_june <- flux_june %>%
  mutate(ecosystem = fct_relevel(ecosystem, c("NWd", "SWd", "Pr", "Wt")))

flux_june %>% 
  ggplot(aes(factor(ecosystem),flux, fill = ecosystem)) +
  geom_violin() +
  facet_grid(gas~., scales = "free") +
  scale_fill_viridis_d(option = "G")

flux_june %>%
  ggplot(aes(factor(ecosystem), flux)) +
  geom_boxplot() +
  facet_grid(gas~., scales = "free")

photo_june <- photo_june %>%
  mutate(ecosystem = fct_relevel(ecosystem, c("SWdP", "PrP", "WtP")))

photo_june %>% 
  ggplot(aes(factor(ecosystem),flux, fill = ecosystem)) +
  geom_violin() +
  scale_fill_viridis_d(option = "G")

photo_june %>%
  ggplot(aes(factor(ecosystem), flux, color = factor(suff))) +
  geom_boxplot()
```

```{r combine-data}
all_june <- bind_rows(flux_june, photo_june)

mod_june <- all_june %>%
  filter(gas == "co2", ecosystem != "NWd") %>%
  mutate(ecosystem = fct_relevel(ecosystem,c("SWd","SWdP","Pr","PrP","Wt","WtP")))

mod_june <- mod_june %>%
  mutate(photo = case_when(ecosystem == "SWdP" ~ TRUE,
                           ecosystem == "PrP" ~ TRUE,
                           ecosystem == "WtP" ~ TRUE,
                           .default = FALSE),
         eco = case_when(ecosystem == "SWdP" ~ "SWd",
                           ecosystem == "PrP" ~ "Pr",
                           ecosystem == "WtP" ~ "Wt",
                         ecosystem == "SWd" ~ "SWd",
                           ecosystem == "Pr" ~ "Pr",
                           ecosystem == "Wt" ~ "Wt"
                         ),
         eco = fct_relevel(eco, c("SWd","Pr", "Wt")))

mod_june <- mod_june %>%
  filter(case_when(photo == TRUE ~ suff == 2,
                   photo == FALSE ~ T)
         )

mod_june %>%
  ggplot(aes(eco, flux)) +
  geom_violin()

```

```{r compare-covered-flux}
mod_june %>%
  ggplot(aes(estimate, flux, color = photo)) +
  geom_point() +
  facet_grid(.~eco, scales = "free")

```

