---
title: "All Months Summary Stats and Visualization"
author: "Michael Yonker"
date: "5/10/23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/cloud/project")
```

```{r load-packages, message= F, include=F}
library(tidyverse)
library(tidymodels)
library(ggh4x)
library(lubridate)

```

```{r read-files, message=F, include = F}
fluxes_aug <- read_csv("data/220818/220818_fluxes.csv")
fluxes_july <- read_csv("data/220712/220712_fluxes.csv")
fluxes_sep <- read_csv("data/220924/220924_fluxes.csv")
fluxes_oct <- read_csv("data/221022/221022_fluxes.csv")
ancillary <- read_csv("data/nachusa-soil-temp-moisture.csv")
```

```{r data-wrangling, include = F, warning = F}
full_moisture <- ancillary %>%
  filter(date != "2022-07-12", method != "oven-dry") %>%
  mutate(ecosystem = case_when(
    site == "big_bowl" ~ "BP",
    site == "small_bowl" ~ "SP",
    site == "east" ~ "EW",
    site == "west" ~ "WW",
    site == "north" ~ "NW",
    site == "south" ~ "SW"
    )) %>%
  mutate(rep = chamber) %>%
  select(c(4,11,6,9,10,2))

full_data <- bind_rows(fluxes_july, fluxes_aug, fluxes_sep, fluxes_oct)

full_data <- full_data %>%
  mutate(date = date.x) %>%
  mutate(date = ymd(date))

full_data <- left_join(full_data, full_moisture, by = c("date", "ecosystem", "rep"))

full_data <- full_data %>%
  mutate(transect = case_when(
    rep <= 4 ~ "high",
    rep <= 8 ~ "mid",
    rep <= 12 ~ "low"
  ))

full_data <- full_data %>%
  select(1:5,17:22)%>%
  mutate(ecosystem = fct_relevel(ecosystem, c(
                                 "SP",
                                 "BP",
                                 "EW",
                                 "WW",
                                 "NW",
                                 "SW")),
         gas = fct_relevel(gas, c(
                                 "co2",
                                 "ch4",
                                 "n2o")),
         transect = fct_relevel(transect, c("high",
                                                     "mid",
                                                     "low"))) 
```

```{r flux-summary, message=F, eval = F}
full_data %>%
  group_by(ecosystem, gas) %>%
  summarize(mean = mean(flux), st_dev = sd(flux)) %>%
  arrange(gas)
```

```{r flux-summary-by-month, message = F, eval=F}
full_data %>%
  group_by(ecosystem, gas, date) %>%
  summarize(mean = mean(flux), st_dev = sd(flux)) %>%
  arrange(gas)
```

```{r overall-mean-fluxes, message = F, eval=F}
full_data %>% 
  group_by(gas, date) %>% 
  summarize(mean = mean(flux), st_dev = sd(flux)) 
```

```{r plot-fluxes, fig.height=7, echo = F, message=F, eval=F}
# full_data %>%
#   filter(gas == "co2") %>%
#   ggplot(aes(rep, flux)) +
#   geom_point() +
#   geom_smooth(method = "lm") +
#   facet_grid(ecosystem~date, scales="free_y") +
#   labs(title = "Carbon dioxide fluxes by ecosystem")
# 
# full_data %>%
#   filter(gas == "co2") %>%
#   ggplot(aes(ecosystem, flux)) +
#   geom_boxplot() +
#   facet_wrap(~date, scales="free_y") +
#   labs(title = "Carbon dioxide boxplots")
# 
# full_data %>%
#   filter(gas == "ch4") %>%
#   ggplot(aes(rep, flux)) +
#   geom_point() +
#   geom_smooth(method = "lm") +
#   facet_grid(ecosystem~date, scales="free_y") +
#   labs(title = "Methane fluxes by ecosystem")
# 
# full_data %>%
#   filter(gas == "ch4") %>%
#   ggplot(aes(ecosystem, flux)) +
#   geom_boxplot() +
#   facet_wrap(~date, scales="free_y") +
#   labs(title = "Methane boxplots")
# 
# full_data %>%
#   filter(gas == "n2o") %>%
#   ggplot(aes(rep, flux)) +
#   geom_point() +
#   geom_smooth(method = "lm") +
#   facet_grid(ecosystem~date, scales="free_y")+
#   labs(title = "Nitrous oxide fluxes by ecosystem")
# 
# full_data %>%
#   filter(gas == "n2o") %>%
#   ggplot(aes(ecosystem, flux)) +
#   geom_boxplot() +
#   facet_wrap(~date, scales="free_y")+
#   labs(title = "Nitrous oxide boxplots")
```

```{r remove-potential-outliers, include=F}
full_data <-
  full_data %>%
  filter( case_when(date != "2022-07-12" ~ T,
                   gas != "ch4" ~ T,
                   ecosystem != "BP" ~ T,
                   rep != 8 ~T)
)

mod_data <-
  full_data %>%
  filter(case_when(date != "2022-08-18" ~ T,
                   gas != "co2" ~ T,
                   ecosystem != "WW" ~ T,
                   rep != 4 ~T))

mod_data <- mod_data %>%
  mutate(am_pm = case_when(
    date == "2022-07-12" & ecosystem == "WW" ~ "AM",
    date == "2022-07-12" & ecosystem == "SW" ~ "AM",
    date == "2022-07-12" & ecosystem == "BP" ~ "AM",
    date == "2022-07-12" & ecosystem == "EW" ~ "PM",
    date == "2022-07-12" & ecosystem == "NW" ~ "PM",
    date == "2022-07-12" & ecosystem == "SP" ~ "PM",
    
    date == "2022-08-18" & ecosystem == "EW" ~ "AM",
    date == "2022-08-18" & ecosystem == "NW" ~ "AM",
    date == "2022-08-18" & ecosystem == "SP" ~ "AM",
    date == "2022-08-18" & ecosystem == "WW" ~ "PM",
    date == "2022-08-18" & ecosystem == "SW" ~ "PM",
    date == "2022-08-18" & ecosystem == "BP" ~ "PM",
    
    date == "2022-09-24" & ecosystem == "WW" ~ "AM",
    date == "2022-09-24" & ecosystem == "SW" ~ "AM",
    date == "2022-09-24" & ecosystem == "SP" ~ "AM",
    date == "2022-09-24" & ecosystem == "EW" ~ "PM",
    date == "2022-09-24" & ecosystem == "NW" ~ "PM",
    date == "2022-09-24" & ecosystem == "BP" ~ "PM",
    
    date == "2022-10-22" & ecosystem == "EW" ~ "AM",
    date == "2022-10-22" & ecosystem == "SW" ~ "AM",
    date == "2022-10-22" & ecosystem == "BP" ~ "AM",
    date == "2022-10-22" & ecosystem == "WW" ~ "PM",
    date == "2022-10-22" & ecosystem == "NW" ~ "PM",
    date == "2022-10-22" & ecosystem == "SP" ~ "PM"
  ))

```

```{r flux-summary-modified, message=F, eval=F}
mod_data %>%
  group_by(ecosystem, gas) %>%
  summarize(mean = mean(flux), st_dev = sd(flux))
```

```{r plot-fluxes-modified, echo=F, message=FALSE, eval = F}
eco.labs <- c("Small Prairie", "Big Prairie", "East Woodlands", "West Woodlands", "North Wetlands", "South Wetlands")
names(eco.labs) <- c("SP", "BP", "EW", "WW", "NW", "SW")
gas.labs <- c("CO2", "CH4", "N2O")
names(gas.labs) <- c("co2", "ch4","n2o")

full_data %>%
  #filter(gas == "co2") %>%
  ggplot(aes(x = ecosystem, y = flux, fill = ecosystem)) +
  geom_violin() +
  facet_grid(gas~., labeller = labeller(gas = gas.labs, ecosystem = eco.labs), scales = "free") +
  labs(title = "GHG fluxes across ecosystems", x = "Ecosystem", y = expression( "Flux ("*mu*"/nmol GHG m"^{-2}*" s"^{-1}*")" ) )+
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/ghg_violins.png")

full_data %>%
  #filter(gas == "co2") %>%
  ggplot(aes(x = factor(date), y = flux, fill = ecosystem)) +
  geom_violin() +
  facet_grid(gas~ecosystem, labeller = labeller(gas = gas.labs, ecosystem = eco.labs), scales = "free") +
  labs(title = "GHG fluxes across ecosystems", x = "Ecosystem", y = expression( "Flux ("*mu*"/nmol GHG m"^{-2}*" s"^{-1}*")" ) )+
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/ghg_violins_across_months.png", height = 14, width = 35)

mod_data %>%
  filter(ecosystem != "SW", gas == "co2") %>%
  ggplot(aes(x = transect, y = flux)) +
  geom_boxplot() +
  facet_grid(ecosystem~gas, labeller = labeller(gas = gas.labs, ecosystem = eco.labs), scales = "free_y") +
  labs(title = "CO2 fluxes across transect positions", x = "Position", y = expression("Flux ("*mu*"mol CO"[2]*" m"^{-2}*" s"^{-1}*")"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/co2_boxplots_eco.png", height = 12)

mod_data %>%
  filter(ecosystem != "SW", gas == "ch4") %>%
  ggplot(aes(x = transect, y = flux)) +
  geom_boxplot() +
  facet_grid(ecosystem~gas, labeller = labeller(gas = gas.labs, ecosystem = eco.labs), scales = "free_y") +
  labs(title = "CH4 fluxes across transect positions", x = "Position", y = expression("Flux (nmol CH"[4]*" m"^{-2}*" s"^{-1}*")"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/ch4_boxplots_eco.png", height = 12)

mod_data %>%
  filter(ecosystem != "SW", gas == "n2o") %>%
  ggplot(aes(x = transect, y = flux)) +
  geom_boxplot() +
  facet_grid(ecosystem~gas, labeller = labeller(gas = gas.labs, ecosystem = eco.labs), scales = "free_y") +
  labs(title = "N2O fluxes across transect positions", x = "Position", y = expression("Flux (nmol N"[2]*"O m"^{-2}*" s"^{-1}*")"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/n2o_boxplots_eco.png", height = 12)

mod_data %>%
  filter(gas == "co2", date != "2022-07-12") %>%
  ggplot(aes(soil_moisture, flux, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", color = "black", fill = "gray50") +
  #facet_grid(.~date.x, labeller = labeller(date.x = date.labs)) +
  labs(title = "CO2 Fluxes vs. Soil Water Content", y = expression("Flux ("*mu*"mol CO"[2]*" m"^{-2}*" s"^{-1}*")"), x = "Water Content (%)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/moisture/co2_flux_n_moisture.png", width = 7, height = 5)

mod_data %>%
  filter(gas == "ch4", date != "2022-07-12") %>%
  ggplot(aes(soil_moisture, flux, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", color = "black", fill = "gray50") +
  #facet_grid(.~date.x, labeller = labeller(date.x = date.labs)) +
  labs(title = "CH4 Fluxes vs. Soil Water Content", y = expression("Flux (nmol CH"[4]*" m"^{-2}*" s"^{-1}*")"), x = "Water Content (%)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/moisture/ch4_flux_n_moisture.png", width = 7, height = 5)

mod_data %>%
  filter(gas == "n2o", date != "2022-07-12") %>%
  ggplot(aes(soil_moisture, flux, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", color = "black", fill = "gray50" ) +
  #facet_grid(.~date.x, labeller = labeller(date.x = date.labs)) +
  labs(title = "N2O Fluxes vs. Soil Water Content", y = expression("Flux (nmol N"[2]*"O m"^{-2}*" s"^{-1}*")"), x = "Water Content (%)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/moisture/n2o_flux_n_moisture.png", width = 7, height = 5)

mod_data %>%
  filter(date != "2022-07-12") %>%
  ggplot(aes(soil_moisture, flux, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", color = "black", fill = "gray50" ) +
  facet_grid(gas~date, scales = "free") +
  labs(title = "Gas Fluxes vs. Soil Water Content Across Months", y = expression("Flux (nmol N"[2]*"O m"^{-2}*" s"^{-1}*")"), x = "Water Content (%)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/moisture/all_flux_n_moisture.png", width = 30, height = 12)

mod_data %>%
  filter(date != "2022-07-12") %>%
  ggplot(aes(factor(date), soil_moisture, fill = ecosystem)) +
  geom_boxplot() +
  #geom_smooth(method = "lm", color = "black", fill = "gray50" ) +
  facet_grid(.~ecosystem, scales = "free") +
  labs(title = "Soil Water Content Across Months", y = "Water Content (%)", x = "Date") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  #guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/moisture/moisture_n_date.png", width = 30, height = 12)

mod_data %>%
  filter(gas == "co2", date != "2022-07-12") %>%
  ggplot(aes(soil_temperature, flux, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", color = "black", fill = "gray50") +
  #facet_grid(.~date.x) +
  labs(title = "CO2 Fluxes vs. Soil Temperature", y = expression("Flux ("*mu*"mol CO"[2]*" m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/co2_flux_n_temp.png", width = 7, height = 5)

mod_data %>%
  filter(gas == "ch4", date != "2022-07-12") %>%
  ggplot(aes(soil_temperature, flux, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", color = "black", fill = "gray50") +
  #facet_grid(.~date.x) +
  labs(title = "CH4 Fluxes vs. Soil Temperature", y = expression("Flux (nmol CH"[4]*" m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/ch4_flux_n_temp.png", width = 7, height = 5)

mod_data %>%
  filter(ecosystem == "EW", date == "2022-08-18") %>%
  ggplot(aes(soil_temperature, flux, fill = factor(rep))) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", color = "black", fill = "gray50") +
  facet_grid(gas~., scales = "free") +
  labs(title = "GHG Fluxes in EW on 8/18", y = expression("Flux (nmol CH"[4]*" m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/EW_weird_temps.png", width = 7, height = 5)

mod_data %>%
  filter(gas == "n2o", date != "2022-07-12") %>%
  ggplot(aes(soil_temperature, flux, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", color = "black", fill = "gray50") +
  #facet_grid(.~date.x) +
  labs(title = "N2O Fluxes vs. Soil Temperature", y = expression("Flux (nmol N"[2]*"O m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/n2o_flux_n_temp.png", width = 7, height = 5)

mod_data %>%
  filter(date != "2022-07-12") %>%
  ggplot(aes(soil_temperature, flux, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", color = "black", fill = "gray50") +
  facet_grid(gas~date, scales = "free") +
  labs(title = "GHG Fluxes vs. Soil Temperature", y = expression( "Flux ("*mu*"/nmol GHG m"^{-2}*" s"^{-1}*")" ), x = "Soil Temperature (°C)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/all_flux_n_temp.png", width = 30, height = 12)

mod_data %>%
  filter(date != "2022-07-12") %>%
  ggplot(aes(soil_temperature, flux, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", color = "black", fill = "gray50") +
  facet_grid(gas~., scales = "free") +
  labs(title = "GHG Fluxes vs. Soil Temperature", y = expression( "Flux ("*mu*"/nmol GHG m"^{-2}*" s"^{-1}*")" ), x = "Soil Temperature (°C)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/all_flux_n_temp_2.png", width = 30, height = 12)

mod_data %>%
  filter(date != "2022-07-12") %>%
  ggplot(aes(factor(date), soil_temperature, fill = ecosystem)) +
  geom_boxplot() +
  #geom_smooth(method = "lm", color = "black", fill = "gray50" ) +
  facet_grid(.~ecosystem, scales = "free") +
  labs(title = "Soil Temperature Across Months ", y = "Soil Temperature (°C)", x = "Date") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  #guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/temp_n_date.png", width = 30, height = 12)

mod_data %>%
  filter(gas == "co2", date != "2022-07-12") %>%
  ggplot(aes(soil_temperature, flux, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", color = "black", fill = "gray50" ) +
  facet_grid(ecosystem~date, scales = "free") +
  labs(title = "CO2 Flux Across Ecosystems and Months", y = expression("Flux ("*mu*"mol CO"[2]*" m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  #guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/eco_facet/co2_temp_date_eco.png", width = 30, height = 12)

mod_data %>%
  filter(gas == "ch4", date != "2022-07-12") %>%
  ggplot(aes(soil_temperature, flux, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", color = "black", fill = "gray50" ) +
  facet_grid(ecosystem~date, scales = "free") +
  labs(title = "CH4 Flux Across Ecosystems and Months", y = expression("Flux (nmol CH"[4]*" m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  #guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/eco_facet/ch4_temp_date_eco.png", width = 30, height = 12)

mod_data %>%
  filter(gas == "n2o", date != "2022-07-12") %>%
  ggplot(aes(soil_temperature, flux, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", color = "black", fill = "gray50" ) +
  facet_grid(ecosystem~date, scales = "free") +
  labs(title = "N2O Flux Across Ecosystems and Months", y = expression("Flux (nmol N"[2]*"O m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  #guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/eco_facet/n2o_temp_date_eco.png", width = 30, height = 12)

mod_data %>%
  filter(date != "2022-07-12") %>%
  ggplot(aes(soil_temperature, soil_moisture, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", color = "black", fill = "gray50" ) +
  facet_grid(am_pm~date, scales = "free") +
  labs(title = "Soil Temperature and Moisture Across Time of Dat", y = "Soil Water Content (%)", x = "Soil Temperature (°C)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  #guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/temp_n_moisture.png", width = 30, height = 12)

mod_data %>%
  filter(gas == "co2", date != "2022-07-12") %>%
  ggplot(aes(soil_temperature, flux, fill = ecosystem, color = am_pm)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", fill = "gray50" ) +
  facet_grid(.~date) +
  labs(title = "CO2 Flux Across Ecosystems and Months", y = expression("Flux ("*mu*"mol CO"[2]*" m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  #guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/ampm/co2_ampm_temp_date_eco.png", width = 30, height = 12)

mod_data %>%
  filter(gas == "ch4", date != "2022-07-12") %>%
  ggplot(aes(soil_temperature, flux, fill = ecosystem, color=am_pm)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", fill = "gray50" ) +
  facet_grid(.~date) +
  labs(title = "CH4 Flux Across Ecosystems and Months", y = expression("Flux (nmol CH"[4]*" m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  #guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/ampm/ch4_ampm_temp_date_eco.png", width = 30, height = 12)

mod_data %>%
  filter(gas == "n2o", date != "2022-07-12") %>%
  ggplot(aes(soil_temperature, flux, fill = ecosystem, color = am_pm)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", fill = "gray50" ) +
  facet_grid(.~date) +
  labs(title = "N2O Flux Across Ecosystems and Months", y = expression("Flux (nmol N"[2]*"O m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  #guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/ampm/n2o_ampm_temp_date_eco.png", width = 30, height = 12)

mod_data %>%
  filter(gas == "co2", date == "2022-08-18") %>%
  ggplot(aes(soil_temperature, flux, color = ecosystem, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", fill = "gray50") +
  facet_grid(am_pm~transect) +
  labs(title = "August CO2 Fluxes vs. Soil Temperature", y = expression("Flux ("*mu*"mol CO"[2]*" m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_color_viridis_d(option = "G",labels = eco.labs) +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/transect_ampm/co2_aug_ampm_flux_n_temp.png", width = 30, height = 12)

mod_data %>%
  filter(gas == "co2", date == "2022-09-24") %>%
  ggplot(aes(soil_temperature, flux, color = ecosystem, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", fill = "gray50") +
  facet_grid(am_pm~transect) +
  labs(title = "September CO2 Fluxes vs. Soil Temperature", y = expression("Flux ("*mu*"mol CO"[2]*" m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_color_viridis_d(option = "G",labels = eco.labs) +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/transect_ampm/co2_sep_ampm_flux_n_temp.png", width = 30, height = 12)

mod_data %>%
  filter(gas == "co2", date == "2022-10-22") %>%
  ggplot(aes(soil_temperature, flux, color = ecosystem, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", fill = "gray50") +
  facet_grid(am_pm~transect) +
  labs(title = "October CO2 Fluxes vs. Soil Temperature", y = expression("Flux ("*mu*"mol CO"[2]*" m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_color_viridis_d(option = "G",labels = eco.labs) +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/transect_ampm/co2_oct_ampm_flux_n_temp.png", width = 30, height = 12)

mod_data %>%
  filter(gas == "ch4", date == "2022-08-18") %>%
  ggplot(aes(soil_temperature, flux, color = ecosystem, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", fill = "gray50") +
  facet_grid(am_pm~transect) +
  labs(title = "August CH4 Fluxes vs. Soil Temperature", y = expression("Flux (nmol CH"[4]*" m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_color_viridis_d(option = "G",labels = eco.labs) +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/transect_ampm/ch4_aug_ampm_flux_n_temp.png", width = 30, height = 12)

mod_data %>%
  filter(gas == "ch4", date == "2022-09-24") %>%
  ggplot(aes(soil_temperature, flux, color = ecosystem, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", fill = "gray50") +
  facet_grid(am_pm~transect) +
  labs(title = "September CH4 Fluxes vs. Soil Temperature", y = expression("Flux (nmol CH"[4]*" m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_color_viridis_d(option = "G",labels = eco.labs) +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/transect_ampm/ch4_sep_ampm_flux_n_temp.png", width = 30, height = 12)

mod_data %>%
  filter(gas == "ch4", date == "2022-10-22") %>%
  ggplot(aes(soil_temperature, flux, color = ecosystem, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", fill = "gray50") +
  facet_grid(am_pm~transect) +
  labs(title = "October CH4 Fluxes vs. Soil Temperature", y = expression("Flux (nmol CH"[4]*" m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_color_viridis_d(option = "G",labels = eco.labs) +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/transect_ampm/ch4_oct_ampm_flux_n_temp.png", width = 30, height = 12)

mod_data %>%
  filter(gas == "n2o", date == "2022-08-18") %>%
  ggplot(aes(soil_temperature, flux, color = ecosystem, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", fill = "gray50") +
  facet_grid(am_pm~transect) +
  labs(title = "August N2O Fluxes vs. Soil Temperature", y = expression("Flux (nmol N"[2]*"O m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_color_viridis_d(option = "G",labels = eco.labs) +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/transect_ampm/n2o_aug_ampm_flux_n_temp.png", width = 30, height = 12)

mod_data %>%
  filter(gas == "n2o", date == "2022-09-24") %>%
  ggplot(aes(soil_temperature, flux, color = ecosystem, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", fill = "gray50") +
  facet_grid(am_pm~transect) +
  labs(title = "September N2O Fluxes vs. Soil Temperature", y = expression("Flux (nmol N"[2]*"O m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_color_viridis_d(option = "G",labels = eco.labs) +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/transect_ampm/n2o_sep_ampm_flux_n_temp.png", width = 30, height = 12)

mod_data %>%
  filter(gas == "n2o", date == "2022-10-22") %>%
  ggplot(aes(soil_temperature, flux, color = ecosystem, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", fill = "gray50") +
  facet_grid(am_pm~transect) +
  labs(title = "October N2O Fluxes vs. Soil Temperature", y = expression("Flux (nmol N"[2]*"O m"^{-2}*" s"^{-1}*")"), x = "Soil Temperature (°C)") +
  scale_color_viridis_d(option = "G",labels = eco.labs) +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/temperature/transect_ampm/n2o_oct_ampm_flux_n_temp.png", width = 30, height = 12)
```

```{r hypothesis-testing}
temp <- mod_data %>%
  group_by(ecosystem, gas, am_pm) %>%
  summarize(mean_flux = mean(flux)) %>%
  pivot_wider(names_from = am_pm, values_from = mean_flux) %>%
  summarize(diff_means = AM - PM) %>%
  ungroup()


# set.seed(9901)
# mod_data %>%
#   #filter(gas == ghg, ecosystem == eco) %>%
#   #group_by(gas, ecosystem) %>%
#   specify(flux ~ ecosystem + gas+ am_pm) %>%
#    hypothesize(null = "independence") %>%
#    generate(reps = 1000, type = "permute") %>%
#    fit()
# 
# %>%
#    summarize(p_value = sum(stat>temp$diff_means[1])/n())


```

```{r hyp-test-function, eval =T, warning = F, echo=F}
options(dplyr.summarise.inform = FALSE)

nachusa_hyp_test <- function(dataframe, n) {
  
statistic <- dataframe %>%
  group_by(ecosystem, gas, am_pm) %>%
  summarize(mean_flux = mean(flux)) %>%
  pivot_wider(names_from = am_pm, values_from = mean_flux) %>%
  summarize(diff_means = AM - PM) %>%
  ungroup()

set.seed(9901)
p_value <- dataframe %>%
  filter(gas == (statistic$gas[n]), ecosystem == (statistic$ecosystem[n]))%>%
  #group_by(gas, ecosystem) %>%
  specify(flux ~ am_pm) %>%
  hypothesize(null = "independence") %>%
  generate(reps = 1000, type = "permute") %>%
  calculate(stat = "diff in means", order = c("AM","PM")) %>%
  summarize(p_value = case_when(
    statistic$diff_means[n]>0 ~ sum(stat>statistic$diff_means[n])/n(), 
    statistic$diff_means[n]<0 ~ sum(stat<statistic$diff_means[n])/n()))

p_value

}

bind_rows(
nachusa_hyp_test(mod_data, 1),
nachusa_hyp_test(mod_data, 2),
nachusa_hyp_test(mod_data, 3),
nachusa_hyp_test(mod_data, 4),
nachusa_hyp_test(mod_data, 5),
nachusa_hyp_test(mod_data, 6),
nachusa_hyp_test(mod_data, 7),
nachusa_hyp_test(mod_data, 8),
nachusa_hyp_test(mod_data, 9),
nachusa_hyp_test(mod_data, 10),
nachusa_hyp_test(mod_data, 11),
nachusa_hyp_test(mod_data, 12),
nachusa_hyp_test(mod_data, 13),
nachusa_hyp_test(mod_data, 14),
nachusa_hyp_test(mod_data, 15),
nachusa_hyp_test(mod_data, 16),
nachusa_hyp_test(mod_data, 17),
nachusa_hyp_test(mod_data, 18)
)%>%
  bind_cols(temp)
```

