---
title: "July and August Summary Stats and Visualization"
author: "Michael Yonker"
date: "3/31/23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/cloud/project")
```

```{r load-packages, message= F, include=F}
library(tidyverse)
library(ggh4x)
library(lubridate)
```

```{r read-files, message=F, include = F}
fluxes_aug <- read_csv("data/220818/220818_fluxes.csv")
fluxes_july <- read_csv("data/220712/220712_fluxes.csv")
ancillary <- read_csv("data/nachusa-soil-temp-moisture.csv")
```

```{r data-wrangling-aug, include = F}
moisture_aug <- ancillary %>%
  filter(date == "2022-08-18") %>%
  mutate(ecosystem = case_when(
    site == "big_bowl" ~ "BP",
    site == "small_bowl" ~ "SP",
    site == "east" ~ "EW",
    site == "west" ~ "WW",
    site == "north" ~ "NW",
    site == "south" ~ "SW"
    )) %>%
  mutate(rep = chamber) %>%
  select(c(4,11,6,9,10))

full_data_aug <- left_join(fluxes_aug, moisture_aug, by = c("ecosystem", "rep"))

```

```{r data-wrangling-july, include = F}
moisture_july <- ancillary %>%
  filter(date == "2022-07-12") %>%
  mutate(ecosystem = case_when(
    site == "big_bowl" ~ "BP",
    site == "small_bowl" ~ "SP",
    site == "east" ~ "EW",
    site == "west" ~ "WW",
    site == "north" ~ "NW",
    site == "south" ~ "SW"
    )) %>%
  mutate(rep = case_when(
    transect == "high" ~ 1,
    transect == "mid" ~ 5,
    transect == "low" ~ 9,
    transect == 1 ~ 1,
    transect == 2 ~ 5,
    transect == 3 ~ 9
    )) %>%
  select(c(4,11,6,9))

full_data_july <- left_join(fluxes_july, moisture_july, by = c("ecosystem", "rep"))

full_data_july <- full_data_july %>%
  rowwise() %>%
  mutate(soil_moisture = list(case_when(
    ecosystem == "BP" & (rep>=1 & rep <=4) ~ 6.8,
    ecosystem == "BP" & (rep>=5 & rep <=8) ~ 8.7,
    ecosystem == "BP" & (rep>=9 & rep <=12) ~ 14.9,
    ecosystem == "EW" & (rep>=1 & rep <=4) ~ 15.9,
    ecosystem == "EW" & (rep>=5 & rep <=8) ~ 14.0,
    ecosystem == "EW" & (rep>=9 & rep <=12) ~ 14.4,
    ecosystem == "NW" & (rep>=1 & rep <=4) ~ 12.9,
    ecosystem == "NW" & (rep>=5 & rep <=8) ~ 3.7,
    ecosystem == "NW" & (rep>=9 & rep <=12) ~ 15.1,
    ecosystem == "SP" & (rep>=1 & rep <=4) ~ 3.9,
    ecosystem == "SP" & (rep>=5 & rep <=8) ~ 13.3,
    ecosystem == "SP" & (rep>=9 & rep <=12) ~ 12.6,
    ecosystem == "SW" & (rep>=1 & rep <=4) ~ 42.2,
    ecosystem == "SW" & (rep>=5 & rep <=8) ~ 23.4,
    ecosystem == "SW" & (rep>=9 & rep <=12) ~ 7.9,
    ecosystem == "WW" & (rep>=1 & rep <=4) ~ 15.4,
    ecosystem == "WW" & (rep>=5 & rep <=8) ~ 6.8,
    ecosystem == "WW" & (rep>=9 & rep <=12) ~ 10.8
  ))) %>%
  mutate(soil_moisture = as.numeric(soil_moisture))
```

```{r flux-summary, message=F}
july_aug_full_data <- bind_rows(full_data_july, full_data_aug)

july_aug_full_data %>%
  group_by(ecosystem, gas) %>%
  summarize(mean = mean(flux), st_dev = sd(flux)) %>% 
  ungroup() %>% 
  group_by(gas) %>% 
  arrange(desc(mean))
```

```{r flux-summary-by-month, message = F}
# july_aug_full_data %>%
#   group_by(ecosystem, gas, factor(date.x)) %>%
#   summarize(mean = mean(flux), st_dev = sd(flux)) %>% 
#   ungroup() %>% 
#   group_by(`factor(date.x)`, gas) %>% 
#   arrange(desc(mean))
```

```{r overall-mean-fluxes, message = F}
# july_aug_full_data %>% 
#   group_by(gas, factor(date.x)) %>% 
#   summarize(mean = mean(flux), st_dev = sd(flux)) 
```

```{r plot-fluxes, fig.height=7, echo = F, message=F}
# july_aug_full_data %>%
#   filter(gas == "co2") %>%
#   ggplot(aes(rep, flux)) +
#   geom_point() +
#   geom_smooth(method = "lm") +
#   facet_grid(ecosystem~date.x) +
#   labs(title = "Carbon dioxide fluxes by ecosystem")
# 
# july_aug_full_data %>%
#   filter(gas == "co2") %>%
#   ggplot(aes(ecosystem, flux)) +
#   geom_boxplot() +
#   facet_wrap(~date.x) +
#   labs(title = "Carbon dioxide boxplots")
# 
# july_aug_full_data %>%
#   filter(gas == "ch4") %>%
#   ggplot(aes(rep, flux)) +
#   geom_point() +
#   geom_smooth(method = "lm") +
#   facet_grid(ecosystem~date.x) +
#   labs(title = "Methane fluxes by ecosystem")
# 
# july_aug_full_data %>%
#   filter(gas == "ch4") %>%
#   ggplot(aes(ecosystem, flux)) +
#   geom_boxplot() +
#   facet_wrap(~date.x) +
#   labs(title = "Methane boxplots")
# 
# july_aug_full_data %>%
#   filter(gas == "n2o") %>%
#   ggplot(aes(rep, flux)) +
#   geom_point() +
#   geom_smooth(method = "lm") +
#   facet_grid(ecosystem~date.x)+
#   labs(title = "Nitrous oxide fluxes by ecosystem")
# 
# july_aug_full_data %>%
#   filter(gas == "n2o") %>%
#   ggplot(aes(ecosystem, flux)) +
#   geom_boxplot() +
#   facet_wrap(~date.x)+
#   labs(title = "Nitrous oxide boxplots")
```

```{r remove-potential-outliers, include=F}
july_aug_full_data <-
  july_aug_full_data %>%
  # filter(case_when(date.x != "220712" ~ T,
  #                  gas != "co2" ~ T,
  #                  ecosystem != "EW" ~ T,
  #                  rep != 2 ~T),
  #        case_when(date.x != "220712" ~ T,
  #                  gas != "co2" ~ T,
  #                  ecosystem != "EW" ~ T,
  #                  rep != 3 ~T),
  #        case_when(date.x != "220712" ~ T,
  #                  gas != "co2" ~ T,
  #                  ecosystem != "NW" ~ T,
  #                  rep != 3 ~T),
  #        case_when(date.x != "220712" ~ T,
  #                  gas != "co2" ~ T,
  #                  ecosystem != "SW" ~ T,
  #                  rep != 9 ~T),
  #        case_when(date.x != "220712" ~ T,
  #                  gas != "co2" ~ T,
  #                  ecosystem != "WW" ~ T,
  #                  rep != 7 ~T),
  #        case_when(date.x != "220818" ~ T,
  #                  gas != "co2" ~ T,
  #                  ecosystem != "WW" ~ T,
  #                  rep != 4 ~T),
  #        case_when(date.x != "220818" ~ T,
  #                  gas != "co2" ~ T,
  #                  ecosystem != "SW" ~ T,
  #                  rep != 12 ~T),
         
      filter( case_when(date.x != "220712" ~ T,
                   gas != "ch4" ~ T,
                   ecosystem != "BP" ~ T,
                   rep != 8 ~T)

         # case_when(date.x != "220818" ~ T,
         #           gas != "ch4" ~ T,
         #           ecosystem != "EW" ~ T,
         #           rep != 2 ~T),
         # case_when(date.x != "220818" ~ T,
         #           gas != "ch4" ~ T,
         #           ecosystem != "EW" ~ T,
         #           rep != 8 ~T),
         # case_when(date.x != "220818" ~ T,
         #           gas != "ch4" ~ T,
         #           ecosystem != "NW" ~ T,
         #           rep != 9 ~T),
         
         # case_when(date.x != "220712" ~ T,
         #           gas != "n2o" ~ T,
         #           ecosystem != "BP" ~ T,
         #           rep != 1 ~T),
         # case_when(date.x != "220712" ~ T,
         #           gas != "n2o" ~ T,
         #           ecosystem != "BP" ~ T,
         #           rep != 2 ~T),
         # case_when(date.x != "220712" ~ T,
         #           gas != "n2o" ~ T,
         #           ecosystem != "BP" ~ T,
         #           rep != 9 ~T),
         # case_when(date.x != "220712" ~ T,
         #           gas != "n2o" ~ T,
         #           ecosystem != "EW" ~ T,
         #           rep != 8 ~T),
         # case_when(date.x != "220712" ~ T,
         #           gas != "n2o" ~ T,
         #           ecosystem != "NW" ~ T,
         #           rep != 8 ~T),
         # case_when(date.x != "220712" ~ T,
         #           gas != "n2o" ~ T,
         #           ecosystem != "NW" ~ T,
         #           rep != 5 ~T),
         # case_when(date.x != "220712" ~ T,
         #           gas != "n2o" ~ T,
         #           ecosystem != "SP" ~ T,
         #           rep != 4 ~T),
         # case_when(date.x != "220712" ~ T,
         #           gas != "n2o" ~ T,
         #           ecosystem != "SP" ~ T,
         #           rep != 10 ~T),
         # case_when(date.x != "220712" ~ T,
         #           gas != "n2o" ~ T,
         #           ecosystem != "SW" ~ T,
         #           rep != 8 ~T),
         # case_when(date.x != "220712" ~ T,
         #           gas != "n2o" ~ T,
         #           ecosystem != "SW" ~ T,
         #           rep != 3 ~T),
         # case_when(date.x != "220818" ~ T,
         #           gas != "n2o" ~ T,
         #           ecosystem != "EW" ~ T,
         #           rep != 6 ~T),
         # case_when(date.x != "220818" ~ T,
         #           gas != "n2o" ~ T,
         #           ecosystem != "SP" ~ T,
         #           rep != 6 ~T),
         # case_when(date.x != "220818" ~ T,
         #           gas != "n2o" ~ T,
         #           ecosystem != "SP" ~ T,
         #           rep != 9 ~T),
         # case_when(date.x != "220818" ~ T,
         #           gas != "n2o" ~ T,
         #           ecosystem != "WW" ~ T,
         #           rep != 1 ~T),
)

july_aug_modified_data <-
  july_aug_full_data %>%
  filter(case_when(date.x != "220818" ~ T,
                   gas != "co2" ~ T,
                   ecosystem != "WW" ~ T,
                   rep != 4 ~T))

```

```{r reorder-ecosystems, warning=FALSE, message = F, echo = F}

july_aug_modified_data <- july_aug_modified_data %>%
  mutate(ecosystem = fct_relevel(ecosystem, levels = c(
                                 "SP",
                                 "BP",
                                 "EW",
                                 "WW",
                                 "NW",
                                 "SW")))

july_aug_full_data <- july_aug_full_data %>%
  mutate(ecosystem = fct_relevel(ecosystem, levels = c(
                                 "SP",
                                 "BP",
                                 "EW",
                                 "WW",
                                 "NW",
                                 "SW")))
```

```{r reorder-gases, message=F, echo=F, warning = F}
july_aug_modified_data <- july_aug_modified_data %>%
  mutate(gas = fct_relevel(gas, levels = c(
                                 "co2",
                                 "ch4",
                                 "n2o")))

july_aug_full_data <- july_aug_full_data %>%
  mutate(gas = fct_relevel(gas, levels = c(
                                 "co2",
                                 "ch4",
                                 "n2o")))
```

```{r rename-dates}
july_aug_modified_data <- july_aug_modified_data %>%
  mutate(date.x = case_when(
    date.x == 220712 ~ "7/12/2022",
    date.x == 220818 ~ "8/18/2022"))
```


```{r flux-summary-modified, message=F}
july_aug_modified_data %>%
  group_by(ecosystem, gas) %>%
  summarize(mean = mean(flux), st_dev = sd(flux))
```

```{r organize-transects, warning = F}
july_aug_modified_data <- july_aug_modified_data %>%
  #filter(ecosystem != "SW") %>%
  mutate(transect = case_when(rep<=4 ~ "low",
                              rep<=8 ~ "mid",
                              rep<=12 ~"high"))

july_aug_modified_data <- july_aug_modified_data %>%
  mutate(transect = fct_relevel(transect, levels = c("high",
                                                     "mid",
                                                     "low"))) %>%
  mutate(transect = fct_rev(transect))

```


```{r plot-fluxes-modified, echo=F, message=FALSE}
eco.labs <- c("Small Prairie", "Big Prairie", "East Woodlands", "West Woodlands", "North Wetlands", "South Wetlands")
names(eco.labs) <- c("SP", "BP", "EW", "WW", "NW", "SW")
# date.labs <- c("7/12/2022","8/18/2022")
# names(date.labs) <- c("220712", "220818")
gas.labs <- c("CO2", "CH4", "N2O")
names(gas.labs) <- c("co2", "ch4","n2o")

# july_aug_modified_data %>%
#   filter(gas == "co2") %>%
#   ggplot(aes(rep, flux)) +
#   geom_point() +
#   geom_smooth(method = "lm") +
#   facet_grid(ecosystem~date.x, labeller = labeller(date.x = date.labs, ecosystem = eco.labs)) +
#   labs(title = "CO2 fluxes by ecosystem", y = "Flux (mg CO2 m-2 d-1)", x = "Chamber ID") +
#   scale_x_continuous(breaks = c(1,5,9,12))
# ggsave("plots/co2_fluxes.png", width = 5, height = 9)

july_aug_full_data %>%
  #filter(gas == "co2") %>%
  ggplot(aes(x = ecosystem, y = flux, fill = ecosystem)) +
  geom_violin() +
  facet_grid(gas~., labeller = labeller(gas = gas.labs, ecosystem = eco.labs), scales = "free") +
  labs(title = "GHG fluxes across ecosystems", x = "Ecosystem", y = expression( "Flux ("*mu*"/nmol GHG m"^{-2}*" s"^{-1}*")" ) )+
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/ghg_violins.png")

# expression("Net CO"[2]*" Flux (nmol m"^{-2}*" s"^{-1}*")"))

# july_aug_modified_data %>%
#   filter(ecosystem != "SW") %>%
#   ggplot(aes(x = transect, y = flux)) +
#   geom_boxplot() +
#   facet_grid(.~gas, labeller = labeller(gas = gas.labs)) +
#   labs(title = "GHG fluxes across transect positions", x = "Position", y = expression("Flux ("*mu*"/nmol GHG m"^{-2}*" s"^{-1}*")"))+
#   theme_bw()
# ggsave("plots/ghg_boxplots.png")

july_aug_modified_data %>%
  filter(ecosystem != "SW") %>%
  ggplot(aes(x = transect, y = flux)) +
  geom_boxplot() +
  facet_grid(ecosystem~gas, labeller = labeller(gas = gas.labs, ecosystem = eco.labs), scales = "free_y") +
  labs(title = "GHG fluxes across transect positions", x = "Position", y = expression("Flux ("*mu*"/nmol GHG m"^{-2}*" s"^{-1}*")"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/ghg_boxplots_eco.png", height = 12)

# july_aug_modified_data %>%
#   filter(gas == "ch4") %>%
#   ggplot(aes(rep, flux)) +
#   geom_point() +
#   geom_smooth(method = "lm") +
#   facet_grid(ecosystem~date.x, labeller = labeller(date.x = date.labs, ecosystem = eco.labs)) +
#   labs(title = "CH4 fluxes by ecosystem", y = "Flux (mug CH4 m-2 d-1)", x = "Chamber ID") +
#   scale_x_continuous(breaks = c(1,5,9,12))
# ggsave("plots/ch4_fluxes.png", width = 5, height = 9)

# july_aug_modified_data %>%
#   filter(gas == "ch4") %>%
#   ggplot(aes(gas, flux)) +
#   geom_violin() +
#   facet_grid(ecosystem~date.x, labeller = labeller(date.x = date.labs, ecosystem = eco.labs)) +
#   labs(title = "CH4 boxplots", y = "Flux (mug CH4 m-2 d-1)", x="") +
#   theme(axis.text.x = element_blank()) 
# ggsave("plots/ch4_violins.png", width = 3, height = 9)

# july_aug_modified_data %>%
#   filter(gas == "n2o") %>%
#   ggplot(aes(rep, flux)) +
#   geom_point() +
#   geom_smooth(method = "lm") +
#   facet_grid(ecosystem~date.x, labeller = labeller(date.x = date.labs, ecosystem = eco.labs)) +
#   labs(title = "N2O fluxes by ecosystem", y = "Flux (mug N2O m-2 d-1)", x = "Chamber ID") +
#   scale_x_continuous(breaks = c(1,5,9,12))
# ggsave("plots/n2o_fluxes.png", width = 5, height = 9)

# july_aug_modified_data %>%
#   filter(gas == "n2o") %>%
#   ggplot(aes(gas, flux)) +
#   geom_violin() +
#   facet_grid(ecosystem~date.x, labeller = labeller(date.x = date.labs, ecosystem = eco.labs)) +
#   labs(title = "N2O boxplots", y = "Flux (mug N2O m-2 d-1)", x="") +
#   theme(axis.text.x = element_blank()) 
# ggsave("plots/n2o_violins.png", width = 3, height = 9)

july_aug_modified_data %>%
  filter(gas == "co2", date.x == "8/18/2022") %>%
  ggplot(aes(soil_moisture, flux, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", color = "black", fill = "gray50") +
  #facet_grid(.~date.x, labeller = labeller(date.x = date.labs)) +
  labs(title = "CO2 Fluxes vs. Soil Water Content", y = expression("Flux ("*mu*"mol CO"[2]*" m"^{-2}*" s"^{-1}*")"), x = "Water Content (%)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/co2_flux_n_moisture.png", width = 7, height = 5)

july_aug_modified_data %>%
  filter(gas == "ch4", date.x == "8/18/2022") %>%
  ggplot(aes(soil_moisture, flux, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", color = "black", fill = "gray50") +
  #facet_grid(.~date.x, labeller = labeller(date.x = date.labs)) +
  labs(title = "CH4 Fluxes vs. Soil Water Content", y = expression("Flux (nmol CH"[4]*" m"^{-2}*" s"^{-1}*")"), x = "Water Content (%)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/ch4_flux_n_moisture.png", width = 7, height = 5)

# july_aug_modified_data %>%
#   filter(gas == "n2o", date.x == "8/18/2022") %>%
#   ggplot(aes(soil_moisture, flux, color = ecosystem)) +
#   geom_point() +
#   geom_smooth(method = "lm", color = "black") +
#   #facet_grid(.~date.x, labeller = labeller(date.x = date.labs)) +
#   labs(title = "N2O Fluxes vs. Soil Water Content", y = "Flux (mug N2O m-2 d-1)", x = "Water Content (%)") +
#   scale_color_discrete(labels = eco.labs) +
#   guides(guide_legend(title = "Ecosystem"))
# ggsave("plots/n2o_flux_n_moisture.png", width = 7, height = 5)

july_aug_modified_data %>%
  filter(gas == "co2", date.x == "8/18/2022") %>%
  ggplot(aes(soil_temperature, flux, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", color = "black", fill = "gray50") +
  #facet_grid(.~date.x) +
  labs(title = "CO2 Fluxes vs. Soil Temperature", y = "Flux (mg CO2 m-2 d-1)", x = "Soil Temperature (°C)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/co2_flux_n_temp.png", width = 7, height = 5)

july_aug_modified_data %>%
  filter(gas == "ch4", date.x == "8/18/2022") %>%
  ggplot(aes(soil_temperature, flux, fill = ecosystem)) +
  geom_point(shape = 21, color = "black", size = 3) +
  geom_smooth(method = "lm", color = "black", fill = "gray50") +
  #facet_grid(.~date.x) +
  labs(title = "CH4 Fluxes vs. Soil Temperature", y = "Flux (mug CH4 m-2 d-1)", x = "Soil Temperature (°C)") +
  scale_fill_viridis_d(option = "G",labels = eco.labs) +
  guides(guide_legend(title = "Ecosystem"))+
  theme_bw() +
  theme(text = element_text(size=20))
ggsave("plots/ch4_flux_n_temp.png", width = 7, height = 5)

# july_aug_modified_data %>%
#   filter(gas == "n2o") %>%
#   ggplot(aes(average_temp_kelvin, flux, color = ecosystem)) +
#   geom_point() +
#   geom_smooth(method = "lm", color = "black") +
#   facet_grid(.~date.x) +
#   labs(title = "N2O Fluxes vs. Average Temperature", y = "Flux (mug N2O m-2 d-1)", x = "Temperature (K)") +
#   scale_color_discrete(labels = eco.labs) +
#   guides(guide_legend(title = "Ecosystem"))
# ggsave("plots/n2o_flux_n_temp.png", width = 7, height = 5)
```
