---
title: "July 12th Exploratory Flux Visualizations"
author: "Michael Yonker"
date: "3/23/23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/cloud/project")
```

```{r load-packages, message= F, include=F}
library(tidyverse)
library(ggh4x)
```

```{r read-files, message=F, include = F}
fluxes_july <- read_csv("data/220712/220712_fluxes.csv")
ancillary <- read_csv("data/nachusa-soil-temp-moisture.csv")
```

```{r data-wrangling, include = F}
moisture_july <- ancillary %>%
  filter(date == "2022-07-12") %>%
  mutate(ecosystem = case_when(
    site == "big_bowl" ~ "BP",
    site == "small_bowl" ~ "SP",
    site == "east" ~ "EW",
    site == "west" ~ "WW",
    site == "north" ~ "NW",
    site == "south" ~ "SW"
    )) %>%
  mutate(rep = case_when(
    transect == "high" ~ 1,
    transect == "mid" ~ 5,
    transect == "low" ~ 9,
    transect == 1 ~ 1,
    transect == 2 ~ 5,
    transect == 3 ~ 9
    )) %>%
  select(c(4,11,9))

full_data_july <- left_join(fluxes_july, moisture_july, by = c("ecosystem", "rep"))

full_data_july <- full_data_july %>%
  rowwise() %>%
  mutate(soil_moisture = list(case_when(
    ecosystem == "BP" & (rep>=1 & rep <=4) ~ 6.8,
    ecosystem == "BP" & (rep>=5 & rep <=8) ~ 8.7,
    ecosystem == "BP" & (rep>=9 & rep <=12) ~ 14.9,
    ecosystem == "EW" & (rep>=1 & rep <=4) ~ 15.9,
    ecosystem == "EW" & (rep>=5 & rep <=8) ~ 14.0,
    ecosystem == "EW" & (rep>=9 & rep <=12) ~ 14.4,
    ecosystem == "NW" & (rep>=1 & rep <=4) ~ 12.9,
    ecosystem == "NW" & (rep>=5 & rep <=8) ~ 3.7,
    ecosystem == "NW" & (rep>=9 & rep <=12) ~ 15.1,
    ecosystem == "SP" & (rep>=1 & rep <=4) ~ 3.9,
    ecosystem == "SP" & (rep>=5 & rep <=8) ~ 13.3,
    ecosystem == "SP" & (rep>=9 & rep <=12) ~ 12.6,
    ecosystem == "SW" & (rep>=1 & rep <=4) ~ 42.2,
    ecosystem == "SW" & (rep>=5 & rep <=8) ~ 23.4,
    ecosystem == "SW" & (rep>=9 & rep <=12) ~ 7.9,
    ecosystem == "WW" & (rep>=1 & rep <=4) ~ 15.4,
    ecosystem == "WW" & (rep>=5 & rep <=8) ~ 6.8,
    ecosystem == "WW" & (rep>=9 & rep <=12) ~ 10.8
  ))) %>%
  mutate(soil_moisture = as.numeric(soil_moisture))
```

```{r read-ppm-data, message=F,include=F}
ppm_data_july<-bind_rows(read_csv("data/220712/220712_t0_ghg_ppm.csv"),
          read_csv("data/220712/220712_t1_ghg_ppm.csv"),
          read_csv("data/220712/220712_t2_ghg_ppm.csv"),
          read_csv("data/220712/220712_t3_ghg_ppm.csv"),
          read_csv("data/220712/220712_t4_ghg_ppm.csv"))
```

```{r find-weird-ch4-flux, include=F}
full_data_july %>%
  filter(gas == "ch4", flux>8)

ppm_data_july %>%
  filter(ecosystem == "BP", rep == 8)
```

```{r ppm-viz, echo=F}
ppm_data_july %>%
  filter(ch4_ppm<9) %>% 
  #group_by(ecosystem) %>%
  filter(ecosystem == "WW") %>%
  ggplot(aes(timepoint, ch4_ppm)) +
  geom_point() +
  facet_nested_wrap(vars(ecosystem,rep), ncol = 3)+
  labs(title = "WW CH4 ppm")
```


```{r flux-viz, echo=F}
full_data_july %>% 
  filter(gas == "ch4") %>%
  filter(case_when(ecosystem != "BP" ~ T, rep != 8 ~ T)) %>%
  ggplot(aes(x = soil_moisture, y = flux, color = factor(rep))) +
  geom_point() +
  labs(title = "CH4 fluxes_july vs. Gravimetric Soil Water Content", y = "Flux (μg CH4 m-2 d-1)", x = "Water Content (%)") +
  facet_wrap(~ecosystem) +
  guides(color = guide_legend(title = "Chamber ID"))

full_data_july %>% 
  filter(gas == "n2o") %>%
  ggplot(aes(x = soil_moisture, y = flux, color = factor(rep))) +
  geom_point() +
  labs(title = "N2O fluxes_july vs. Gravimetric Soil Water Content", y = "Flux (μg N2O m-2 d-1)", x = "Water Content (%)") +
  facet_wrap(~ecosystem) +
  guides(color = guide_legend(title = "Chamber ID"))

full_data_july %>% 
  filter(gas == "co2") %>%
  ggplot(aes(x = soil_moisture, y = flux, color = factor(rep))) +
  geom_point() +
  labs(title = "CO2 fluxes_july vs. Gravimetric Soil Water Content", y = "Flux (mg CO2 m-2 d-1)", x = "Water Content (%)") +
  facet_wrap(~ecosystem) +
  guides(color = guide_legend(title = "Chamber ID"))
```

```{r moisture-viz, warning=F, echo=F}
full_data_july %>% 
  filter(gas == "ch4", p.value < .05) %>%
  ggplot(aes(x = soil_moisture, y = p.value, color = factor(rep))) +
  geom_point() +
  labs(title = "Significant CH4 p-values vs. Gravimetric Soil Water Content", y = "p-value", x = "Water Content (%)") +
  facet_wrap(~ecosystem) +
  guides(color = guide_legend(title = "Chamber ID")) +
  scale_y_reverse()

full_data_july %>% 
  filter(gas == "n2o", p.value < .05) %>%
  ggplot(aes(x = soil_moisture, y = p.value, color = factor(rep))) +
  geom_point() +
  labs(title = "Significant N2O p-values vs. Gravimetric Soil Water Content", y = "p-value", x = "Water Content (%)") +
  facet_wrap(~ecosystem) +
  guides(color = guide_legend(title = "Chamber ID")) +
  scale_y_reverse()

full_data_july %>% 
  filter(gas == "co2", p.value < .05) %>%
  ggplot(aes(x = soil_moisture, y = p.value, color = factor(rep))) +
  geom_point() +
  labs(title = "Significant CO2 p-values vs. Gravimetric Soil Water Content", y = "p-value", x = "Water Content (%)") +
  facet_wrap(~ecosystem) +
  guides(color = guide_legend(title = "Chamber ID")) +
  scale_y_reverse()
```
